extends AttackEffectData
class_name SetWeaponTypeEffect

@export var weapon_type: String = "tear"
@export var damage_multiplier: float = 1.0
@export var beam_segment_count: int = 8
@export var beam_segment_spacing: float = 14.0
@export var beam_segment_duration: float = 0.16
@export var blade_outbound_distance: float = 72.0
@export var blade_return_speed: float = 260.0
@export var blade_spin_speed: float = 16.0
@export var blade_contact_cooldown: float = 0.2
@export var ring_expand_rate: float = 180.0
@export var ring_max_radius: float = 84.0
@export var ring_lifetime: float = 0.6
@export var ring_contact_cooldown: float = 0.15
@export var remote_speed: float = 120.0
@export var remote_turn_rate: float = 5.0
@export var remote_lifetime: float = 5.0
@export var remote_contact_cooldown: float = 0.12
@export var orbit_radius: float = 64.0
@export var orbit_angular_speed: float = 3.5
@export var orbit_duration: float = 2.0
@export var orbit_radial_drift: float = 8.0
@export var orbit_contact_cooldown: float = 0.16
@export var lob_gravity: float = 420.0
@export var lob_burst_count: int = 6
@export var lob_burst_spread_degrees: float = 360.0
@export var lob_burst_speed_multiplier: float = 0.65
@export var lob_burst_damage_multiplier: float = 0.5
@export var lob_burst_inherit_status: bool = true
@export var elastic_bonus_bounces: int = 8
@export var elastic_min_bounces: int = 4
@export var elastic_speed_retention: float = 0.94
@export var elastic_random_angle_degrees: float = 20.0
@export var charge_enabled: bool = false
@export var charge_min_time: float = 0.1
@export var charge_max_time: float = 1.0
@export var charge_damage_scale_min: float = 0.7
@export var charge_damage_scale_max: float = 1.8
@export var charge_speed_scale_min: float = 0.9
@export var charge_speed_scale_max: float = 1.1
@export var charge_range_scale_min: float = 0.9
@export var charge_range_scale_max: float = 1.25
@export var charge_split_min: int = 0
@export var charge_split_max: int = 0
@export var charge_size_scale_min: float = 0.9
@export var charge_size_scale_max: float = 1.5
@export var continuous_fire: bool = false
@export var continuous_tick_rate: float = 0.07

func apply_to_attack_data(attack_data: AttackData) -> void:
	attack_data.weapon_type = weapon_type
	attack_data.damage *= max(0.0, damage_multiplier)
	attack_data.beam_segment_count = max(1, beam_segment_count)
	attack_data.beam_segment_spacing = max(1.0, beam_segment_spacing)
	attack_data.beam_segment_duration = max(0.05, beam_segment_duration)
	attack_data.blade_outbound_distance = max(16.0, blade_outbound_distance)
	attack_data.blade_return_speed = max(1.0, blade_return_speed)
	attack_data.blade_spin_speed = blade_spin_speed
	attack_data.blade_contact_cooldown = max(0.03, blade_contact_cooldown)
	attack_data.ring_expand_rate = max(1.0, ring_expand_rate)
	attack_data.ring_max_radius = max(8.0, ring_max_radius)
	attack_data.ring_lifetime = max(0.05, ring_lifetime)
	attack_data.ring_contact_cooldown = max(0.03, ring_contact_cooldown)
	attack_data.remote_speed = max(1.0, remote_speed)
	attack_data.remote_turn_rate = max(0.1, remote_turn_rate)
	attack_data.remote_lifetime = max(0.2, remote_lifetime)
	attack_data.remote_contact_cooldown = max(0.03, remote_contact_cooldown)
	attack_data.orbit_radius = max(8.0, orbit_radius)
	attack_data.orbit_angular_speed = orbit_angular_speed
	attack_data.orbit_duration = max(0.05, orbit_duration)
	attack_data.orbit_radial_drift = orbit_radial_drift
	attack_data.orbit_contact_cooldown = max(0.03, orbit_contact_cooldown)
	attack_data.lob_gravity = max(0.0, lob_gravity)
	attack_data.lob_burst_count = max(1, lob_burst_count)
	attack_data.lob_burst_spread_degrees = max(1.0, lob_burst_spread_degrees)
	attack_data.lob_burst_speed_multiplier = max(0.0, lob_burst_speed_multiplier)
	attack_data.lob_burst_damage_multiplier = max(0.0, lob_burst_damage_multiplier)
	attack_data.lob_burst_inherit_status = lob_burst_inherit_status
	attack_data.elastic_bonus_bounces = max(0, elastic_bonus_bounces)
	attack_data.elastic_min_bounces = max(0, elastic_min_bounces)
	attack_data.elastic_speed_retention = clamp(elastic_speed_retention, 0.05, 1.5)
	attack_data.elastic_random_angle_degrees = clamp(elastic_random_angle_degrees, 0.0, 180.0)
	attack_data.charge_enabled = charge_enabled
	attack_data.charge_min_time = max(0.01, charge_min_time)
	attack_data.charge_max_time = max(attack_data.charge_min_time, charge_max_time)
	attack_data.charge_damage_scale_min = max(0.0, charge_damage_scale_min)
	attack_data.charge_damage_scale_max = max(attack_data.charge_damage_scale_min, charge_damage_scale_max)
	attack_data.charge_speed_scale_min = max(0.0, charge_speed_scale_min)
	attack_data.charge_speed_scale_max = max(attack_data.charge_speed_scale_min, charge_speed_scale_max)
	attack_data.charge_range_scale_min = max(0.0, charge_range_scale_min)
	attack_data.charge_range_scale_max = max(attack_data.charge_range_scale_min, charge_range_scale_max)
	attack_data.charge_split_min = max(0, charge_split_min)
	attack_data.charge_split_max = max(attack_data.charge_split_min, charge_split_max)
	attack_data.charge_size_scale_min = max(0.1, charge_size_scale_min)
	attack_data.charge_size_scale_max = max(attack_data.charge_size_scale_min, charge_size_scale_max)
	attack_data.continuous_fire = continuous_fire
	attack_data.continuous_tick_rate = max(0.02, continuous_tick_rate)
