class_name AttackData extends RefCounted

var direction: Vector2 = Vector2.ZERO
var inherited_velocity: Vector2 = Vector2.ZERO
var damage: float = 1.0
var speed: float = 150.0
var max_distance: float = 150.0
var movement_inheritance: float = 0.4
var infection_shot: bool = false
var source_luck: float = 0.0
var charge_enabled: bool = false
var charge_min_time: float = 0.1
var charge_max_time: float = 1.0
var charge_damage_scale_min: float = 0.7
var charge_damage_scale_max: float = 1.8
var charge_speed_scale_min: float = 0.9
var charge_speed_scale_max: float = 1.1
var charge_range_scale_min: float = 0.9
var charge_range_scale_max: float = 1.25
var charge_split_min: int = 0
var charge_split_max: int = 0
var charge_size_scale_min: float = 0.9
var charge_size_scale_max: float = 1.5
var continuous_fire: bool = false
var continuous_tick_rate: float = 0.07
var fracture_on_hit_count: int = 0
var fracture_spread_degrees: float = 26.0
var fracture_damage_multiplier: float = 0.5
var fracture_speed_multiplier: float = 1.0
var fracture_range_multiplier: float = 0.6
var fracture_generations: int = 1
var pierce_count: int = 0
var bounce_count: int = 0
var weapon_type: String = "tear"
var beam_segment_count: int = 8
var beam_segment_spacing: float = 14.0
var beam_segment_duration: float = 0.16
var homing_strength: float = 0.0
var homing_radius: float = 0.0
var split_count: int = 0
var split_spread_degrees: float = 12.0
var chance_split_count: int = 0
var chance_split_spread_degrees: float = 12.0
var chance_split_chance: float = 0.0
var chance_split_luck_to_full: float = 0.0
var chance_split_max_chance: float = 1.0
var spectral: bool = false
var crit_chance: float = 0.0
var crit_multiplier: float = 1.5
var crit_luck_to_full: float = 0.0
var crit_max_chance: float = 1.0
var knockback_multiplier: float = 1.0
var knockback_flat_bonus: float = 0.0
var explosion_radius: float = 0.0
var explosion_damage_multiplier: float = 1.0
var explosion_inherits_infection: bool = false
var explosion_spawn_count: int = 0
var explosion_spawn_spread_degrees: float = 360.0
var explosion_spawn_damage_multiplier: float = 0.35
var explosion_spawn_speed_multiplier: float = 1.0
var explosion_spawn_range_multiplier: float = 0.5
var explosion_spawn_inherit_status: bool = false
var status_payloads: Array[StatusPayload] = []
var blade_outbound_distance: float = 72.0
var blade_return_speed: float = 260.0
var blade_spin_speed: float = 16.0
var blade_contact_cooldown: float = 0.2
var ring_expand_rate: float = 180.0
var ring_max_radius: float = 84.0
var ring_lifetime: float = 0.6
var ring_contact_cooldown: float = 0.15
var remote_speed: float = 120.0
var remote_turn_rate: float = 5.0
var remote_lifetime: float = 5.0
var remote_contact_cooldown: float = 0.12
var orbit_radius: float = 64.0
var orbit_angular_speed: float = 3.5
var orbit_duration: float = 2.0
var orbit_radial_drift: float = 8.0
var orbit_contact_cooldown: float = 0.16
var lob_gravity: float = 420.0
var lob_burst_count: int = 6
var lob_burst_spread_degrees: float = 360.0
var lob_burst_speed_multiplier: float = 0.65
var lob_burst_damage_multiplier: float = 0.5
var lob_burst_inherit_status: bool = true
var elastic_bonus_bounces: int = 8
var elastic_min_bounces: int = 4
var elastic_speed_retention: float = 0.94
var elastic_random_angle_degrees: float = 20.0
var bounce_speed_retention: float = 1.0
var bounce_random_angle_degrees: float = 0.0
var appended_shot_offsets: Array[float] = []
var cadence_interval: int = 0
var cadence_shot_split_bonus: int = 0
var cadence_shot_damage_multiplier: float = 1.0
var cadence_shot_explosion_radius: float = 0.0

func copy() -> AttackData:
	var cloned := AttackData.new()
	cloned.direction = direction
	cloned.inherited_velocity = inherited_velocity
	cloned.damage = damage
	cloned.speed = speed
	cloned.max_distance = max_distance
	cloned.movement_inheritance = movement_inheritance
	cloned.infection_shot = infection_shot
	cloned.source_luck = source_luck
	cloned.charge_enabled = charge_enabled
	cloned.charge_min_time = charge_min_time
	cloned.charge_max_time = charge_max_time
	cloned.charge_damage_scale_min = charge_damage_scale_min
	cloned.charge_damage_scale_max = charge_damage_scale_max
	cloned.charge_speed_scale_min = charge_speed_scale_min
	cloned.charge_speed_scale_max = charge_speed_scale_max
	cloned.charge_range_scale_min = charge_range_scale_min
	cloned.charge_range_scale_max = charge_range_scale_max
	cloned.charge_split_min = charge_split_min
	cloned.charge_split_max = charge_split_max
	cloned.charge_size_scale_min = charge_size_scale_min
	cloned.charge_size_scale_max = charge_size_scale_max
	cloned.continuous_fire = continuous_fire
	cloned.continuous_tick_rate = continuous_tick_rate
	cloned.fracture_on_hit_count = fracture_on_hit_count
	cloned.fracture_spread_degrees = fracture_spread_degrees
	cloned.fracture_damage_multiplier = fracture_damage_multiplier
	cloned.fracture_speed_multiplier = fracture_speed_multiplier
	cloned.fracture_range_multiplier = fracture_range_multiplier
	cloned.fracture_generations = fracture_generations
	cloned.pierce_count = pierce_count
	cloned.bounce_count = bounce_count
	cloned.weapon_type = weapon_type
	cloned.beam_segment_count = beam_segment_count
	cloned.beam_segment_spacing = beam_segment_spacing
	cloned.beam_segment_duration = beam_segment_duration
	cloned.homing_strength = homing_strength
	cloned.homing_radius = homing_radius
	cloned.split_count = split_count
	cloned.split_spread_degrees = split_spread_degrees
	cloned.chance_split_count = chance_split_count
	cloned.chance_split_spread_degrees = chance_split_spread_degrees
	cloned.chance_split_chance = chance_split_chance
	cloned.chance_split_luck_to_full = chance_split_luck_to_full
	cloned.chance_split_max_chance = chance_split_max_chance
	cloned.spectral = spectral
	cloned.crit_chance = crit_chance
	cloned.crit_multiplier = crit_multiplier
	cloned.crit_luck_to_full = crit_luck_to_full
	cloned.crit_max_chance = crit_max_chance
	cloned.knockback_multiplier = knockback_multiplier
	cloned.knockback_flat_bonus = knockback_flat_bonus
	cloned.explosion_radius = explosion_radius
	cloned.explosion_damage_multiplier = explosion_damage_multiplier
	cloned.explosion_inherits_infection = explosion_inherits_infection
	cloned.explosion_spawn_count = explosion_spawn_count
	cloned.explosion_spawn_spread_degrees = explosion_spawn_spread_degrees
	cloned.explosion_spawn_damage_multiplier = explosion_spawn_damage_multiplier
	cloned.explosion_spawn_speed_multiplier = explosion_spawn_speed_multiplier
	cloned.explosion_spawn_range_multiplier = explosion_spawn_range_multiplier
	cloned.explosion_spawn_inherit_status = explosion_spawn_inherit_status
	cloned.status_payloads = clone_status_payloads()
	cloned.blade_outbound_distance = blade_outbound_distance
	cloned.blade_return_speed = blade_return_speed
	cloned.blade_spin_speed = blade_spin_speed
	cloned.blade_contact_cooldown = blade_contact_cooldown
	cloned.ring_expand_rate = ring_expand_rate
	cloned.ring_max_radius = ring_max_radius
	cloned.ring_lifetime = ring_lifetime
	cloned.ring_contact_cooldown = ring_contact_cooldown
	cloned.remote_speed = remote_speed
	cloned.remote_turn_rate = remote_turn_rate
	cloned.remote_lifetime = remote_lifetime
	cloned.remote_contact_cooldown = remote_contact_cooldown
	cloned.orbit_radius = orbit_radius
	cloned.orbit_angular_speed = orbit_angular_speed
	cloned.orbit_duration = orbit_duration
	cloned.orbit_radial_drift = orbit_radial_drift
	cloned.orbit_contact_cooldown = orbit_contact_cooldown
	cloned.lob_gravity = lob_gravity
	cloned.lob_burst_count = lob_burst_count
	cloned.lob_burst_spread_degrees = lob_burst_spread_degrees
	cloned.lob_burst_speed_multiplier = lob_burst_speed_multiplier
	cloned.lob_burst_damage_multiplier = lob_burst_damage_multiplier
	cloned.lob_burst_inherit_status = lob_burst_inherit_status
	cloned.elastic_bonus_bounces = elastic_bonus_bounces
	cloned.elastic_min_bounces = elastic_min_bounces
	cloned.elastic_speed_retention = elastic_speed_retention
	cloned.elastic_random_angle_degrees = elastic_random_angle_degrees
	cloned.bounce_speed_retention = bounce_speed_retention
	cloned.bounce_random_angle_degrees = bounce_random_angle_degrees
	cloned.appended_shot_offsets = appended_shot_offsets.duplicate()
	cloned.cadence_interval = cadence_interval
	cloned.cadence_shot_split_bonus = cadence_shot_split_bonus
	cloned.cadence_shot_damage_multiplier = cadence_shot_damage_multiplier
	cloned.cadence_shot_explosion_radius = cadence_shot_explosion_radius
	return cloned

func clone_status_payloads() -> Array[StatusPayload]:
	var cloned_payloads: Array[StatusPayload] = []
	for payload in status_payloads:
		if payload == null:
			continue
		cloned_payloads.append(payload.copy())
	return cloned_payloads
